/* Destruction Simulator — local, dependency-bundled destruction playground. */
'use strict';
const $=id=>document.getElementById(id);
const names=['The Hammer','Sledgehammer','Crowbar','Steel Bat','Wrecking Maul','Pickaxe','Fire Axe','Concrete Club','Twin Hammers','Demolition Fist','Spiked Mace','Iron Ram','Jackhammer','War Hammer','Titan Mallet','Chain Flail','Hydraulic Punch','Rock Crusher','Shock Baton','Seismic Hammer','Gravity Glove','Air Cannon','Vortex Gauntlet','Magnetic Fist','Thunder Mallet','Ice Breaker','Flame Knuckles','Quake Boots','Sonic Ram','Plasma Blade','Pulse Gauntlet','Meteor Hammer','Tesla Staff','Cyclone Mace','Lava Maul','Frost Nova','Gravity Slam','Solar Spear','Void Axe','Storm Breaker','Atom Smasher','Orbital Fist','Singularity Staff','Neon Scythe','Comet Maul','Antimatter Club','Reality Breaker','Planet Cracker','Infinity Hammer','Pistol','Heavy Revolver','Machine Pistol','Double Barrel','Pump Shotgun','Compact SMG','Burst Rifle','Assault Rifle','Marksman Rifle','Heavy Shotgun','Sniper Rifle','Drum SMG','Battle Rifle','Auto Shotgun','Light Machine Gun','Heavy Machine Gun','Grenade Launcher','Rocket Launcher','Flare Blaster','Plasma Pistol','Laser Carbine','Tesla Rifle','Cryo Cannon','Flame Cannon','Railgun','Gauss Rifle','Sonic Blaster','Pulse Rifle','Arc Cannon','Gravity Gun','Shard Launcher','Acid Blaster','Lava Launcher','Vortex Rifle','Photon Cannon','Neutron Rifle','Missile Swarm','Cluster Launcher','Minigun','Thunder Cannon','Meteor Launcher','Orbital Marker','Black Hole Gun','Antimatter Rifle','Supernova Cannon','Quantum Blaster','Void Launcher','Star Destroyer','World Eater','Reality Cannon','The Final Argument'];
const weapons=names.map((name,i)=>({name,level:i+1,gun:i>=49,power:i<49?2+Math.floor(i/7):5+Math.floor((i-49)/5),radius:i<49?2.1+i*.035:2.8+(i-49)*.055,cooldown:i<49?.52:i%5===0?.15:.34}));
let saved={};try{saved=JSON.parse(localStorage.getItem('wreck-save')||'{}')}catch{}
const progression=Progression.load(saved);
let selected=Math.min(99,Math.max(0,Math.floor(Number(saved?.selected)||0)));
const level=()=>progression.level; if(selected>=level())selected=0;
const scene=new THREE.Scene();scene.background=new THREE.Color('#8bada5');scene.fog=new THREE.FogExp2('#8bada5',.012);
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,180);
scene.add(new THREE.HemisphereLight(0xd9f3e6,0x58644b,2));const sun=new THREE.DirectionalLight(0xffe8bb,3);sun.position.set(-20,35,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,far:100});sun.shadow.bias=-.001;scene.add(sun);
const geo=new THREE.BoxGeometry(1,1,1),materials={};function mat(color){return materials[color]||(materials[color]=new THREE.MeshStandardMaterial({color,roughness:.85}));}
function box(x,y,z,w,h,d,color,parent=scene){const mesh=new THREE.Mesh(geo,mat(color));mesh.position.set(x,y,z);mesh.scale.set(w,h,d);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
box(0,-.3,0,120,.6,120,'#667565');box(0,-.025,0,43,.05,38,'#8b9584');
const grid=new THREE.GridHelper(42,28,0x929d8a,0x929d8a);grid.position.y=.016;scene.add(grid);
for(let x=-21;x<=21;x+=3){box(x,.015,18,.95,.035,.16,'#e3d4a0');box(x,.015,-18,.95,.035,.16,'#e3d4a0')}
function sign(text,x,y,z,w=5){const cv=document.createElement('canvas');cv.width=512;cv.height=128;const c=cv.getContext('2d');c.fillStyle='#203630';c.fillRect(0,0,512,128);c.fillStyle='#cbff68';c.font='bold 50px Arial';c.textAlign='center';c.fillText(text,256,82);const m=new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(cv),side:THREE.DoubleSide}));m.position.set(x,y,z);scene.add(m)}
sign('THE WORKS / 01',0,7,-19,9);box(-4,3.3,-19,.15,7,.15,'#384d44');box(4,3.3,-19,.15,7,.15,'#384d44');
for(let i=0;i<22;i++){const x=(i%11-5)*7,z=i<11?-34:34;box(x,2+((i*7)%5),z,5,4+((i*7)%10),6,i%2?'#71877a':'#809185')}
for(let x=-24;x<=24;x+=4){box(x,1.5,-22,.1,3,.1,'#40584c');box(x,1.5,22,.1,3,.1,'#40584c')}for(const z of [-22,22]){box(0,1,z,48,.06,.06,'#40584c');box(0,2,z,48,.06,.06,'#40584c')}
for(let i=0;i<9;i++){let x=-19+i*4.7;box(x,.3,16,1.6,.6,.6,'#d4ad45');for(let j=0;j<3;j++)box(x-.5+j*.5,.61,16,.2,.03,.61,'#3e493c')}
// Industrial crane and shipping containers frame the playable yard.
box(16,7,-15,.6,14,.6,'#b49e54');box(10,13.5,-15,13,.5,.5,'#b49e54');box(5,10,-15,.035,7,.035,'#394e45');box(5,6.5,-15,1,.2,.7,'#394e45');
for(let j=0;j<2;j++){box(-18,1.3+j*2.6,-11,4,2.5,7,j?'#a7744e':'#46685e');for(let i=0;i<10;i++)box(-18,1.3+j*2.6,-14+i*.65,4.03,2.4,.045,j?'#8d6244':'#3d5b52')}
const player=new THREE.Group();scene.add(player);player.position.set(0,0,11);
// Rounded anatomy with shoulder, hip, elbow, and knee joints.
const roundGeo=new THREE.SphereGeometry(1,16,12);
function rounded(x,y,z,w,h,d,color,parent=player){const mesh=new THREE.Mesh(roundGeo,mat(color));mesh.position.set(x,y,z);mesh.scale.set(w,h,d);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function joint(x,y,z,parent=player){const group=new THREE.Group();group.position.set(x,y,z);parent.add(group);return group;}
rounded(0,1.28,0,.31,.4,.18,'#d8b744'); // fitted work vest
rounded(0,.98,0,.255,.17,.17,'#30444d');
rounded(0,1.64,0,.09,.14,.09,'#c8906b');
rounded(0,1.84,-.015,.17,.23,.16,'#d9a07c');
rounded(-.17,1.83,0,.035,.065,.04,'#c8906b');rounded(.17,1.83,0,.035,.065,.04,'#c8906b');
rounded(0,1.82,-.174,.038,.05,.055,'#c8906b');
for(const x of [-.065,.065]){rounded(x,1.9,-.151,.035,.021,.017,'#f1eee3');rounded(x,1.9,-.166,.013,.016,.008,'#303a36');}
rounded(0,1.75,-.151,.053,.012,.015,'#865844');
rounded(0,2.015,0,.2,.115,.19,'#f0cc46');rounded(0,1.985,-.035,.23,.025,.235,'#ddb52d');
for(const x of [-.16,.16]){box(x,1.32,.164,.052,.48,.018,'#e0e4bc',player);box(x,1.32,-.165,.052,.48,.018,'#e0e4bc',player)}
box(0,1.15,.177,.5,.045,.025,'#e0e4bc',player);box(0,1.02,0,.49,.075,.34,'#4b4138',player);
function leg(x){const hip=joint(x,.97,0);rounded(0,-.21,0,.125,.26,.135,'#344c58',hip);const knee=joint(0,-.43,0,hip);rounded(0,-.17,0,.10,.23,.11,'#344c58',knee);rounded(0,-.38,-.065,.12,.10,.21,'#423d34',knee);rounded(0,0,-.09,.085,.105,.045,'#566970',knee);hip.userData.knee=knee;return hip;}
const legL=leg(-.15),legR=leg(.15);
function makeArm(x){const shoulder=joint(x,1.52,0);rounded(0,-.10,0,.13,.19,.13,'#6e7770',shoulder);rounded(0,-.28,0,.08,.13,.085,'#c8906b',shoulder);rounded(0,-.40,-.035,.075,.14,.075,'#d9a07c',shoulder);rounded(0,-.54,-.055,.083,.095,.08,'#4c4939',shoulder);return shoulder;}
const leftArm=makeArm(-.34),arm=makeArm(.34);const tool=new THREE.Group();arm.add(tool);box(0,-.55,-.27,.065,.065,.72,'#7a624a',tool);const head=box(0,-.55,-.65,.55,.3,.3,'#c9d1c4',tool);
let blocks=[],fragments=[],effects=[],destroyed=0,initialCount=0,score=0,started=false,yaw=0,pitch=.2,vy=0,grounded=true,cooldown=0,swing=0,shake=0,last=performance.now(),clock=0,toastUntil=6;
function addBlock(x,y,z,color){const mesh=box(x,y,z,1.12,.65,.65,color);blocks.push({mesh,hp:2+Math.floor(y/2),alive:true,falling:false,vy:0});}
function build(){blocks.forEach(b=>scene.remove(b.mesh));fragments.forEach(b=>scene.remove(b.mesh));blocks=[];fragments=[];destroyed=0;
for(let row=0;row<8;row++)for(let col=0;col<10;col++){if(row<4&&(col===4||col===5))continue;addBlock(-5.1+col*1.15,.34+row*.68,-2,row%3===0?'#cfaa76':'#b9895d')}
for(const side of [-1,1])for(let row=0;row<8;row++)for(let col=0;col<6;col++)addBlock(side*5.2,.34+row*.68,-2-col*.68,row%3===0?'#cfaa76':'#b9895d');
for(let row=0;row<5;row++)for(let col=0;col<7;col++)addBlock(-12+col*1.15,.34+row*.68,5,'#a6b0a0');
for(let row=0;row<6;row++)for(let col=0;col<5;col++)addBlock(8+col*1.15,.34+row*.68,2,row%2?'#789a8f':'#97b0a1');
for(let row=0;row<5;row++)for(let col=0;col<5-row;col++)addBlock(-2+col*1.15,.34+row*.68,-12,'#bd8e52');initialCount=blocks.length;updateHUD();}
function persist(){try{localStorage.setItem('wreck-save',JSON.stringify({version:3,level:level(),xp:progression.xp.toString(),selected}))}catch{}}
function updateHUD(){const w=weapons[selected];$('level').textContent=String(level()).padStart(2,'0');$('xp').textContent=level()===100?'MAX LEVEL':`${progression.xp.toLocaleString()} / ${Progression.required(level()).toLocaleString()} XP`;$('xpBar').style.width=(level()===100?100:Number(progression.xp*10000n/Progression.required(level()))/100)+'%';$('score').textContent=String(score).padStart(6,'0').replace(/(\d{3})$/ ,',$1');$('objective').textContent=`${destroyed} / ${initialCount} blocks destroyed`;$('weaponName').textContent=w.name;$('weaponType').textContent=w.gun?'BALLISTICS / TECH':selected>19?'EXPERIMENTAL / POWER':'DEMOLITION / MELEE';$('weaponDetail').textContent=w.gun?'RANGED IMPACT • UNLIMITED AMMO':'HEAVY IMPACT • UNLIMITED USE';$('nextUnlock').textContent=level()<100?`NEXT: ${weapons[level()].name.toUpperCase()} AT LEVEL ${level()+1}${level()<50?' • GUNS AT LVL 50':''}`:'ALL 100 WEAPONS UNLOCKED';head.scale.set(w.gun?.18:.55,w.gun?.18:.3,w.gun?1:.3);}
function toast(message){$('toast').textContent=message;$('toast').style.opacity=1;toastUntil=clock+4;}
function shatter(b,direction){if(!b.alive)return;b.alive=false;scene.remove(b.mesh);destroyed++;score+=125;const old=level();Progression.award(progression,12);if(level()>old){toast(`LEVEL ${level()} — ${weapons[level()-1].name.toUpperCase()} UNLOCKED!`);persist()}
for(let i=0;i<5;i++){const mesh=box(b.mesh.position.x+(Math.random()-.5)*.7,b.mesh.position.y,b.mesh.position.z,.2+Math.random()*.3,.2+Math.random()*.2,.2+Math.random()*.3,b.mesh.material.color.getHex());fragments.push({mesh,v:new THREE.Vector3(direction.x*(3+Math.random()*5)+(Math.random()-.5)*3,2+Math.random()*5,direction.z*(3+Math.random()*5)+(Math.random()-.5)*3),rot:new THREE.Vector3(Math.random()*5,Math.random()*5,Math.random()*5),life:8})}
while(fragments.length>260)scene.remove(fragments.shift().mesh);if(destroyed===initialCount){toast('YARD CLEARED! +500 XP · Press R to rebuild.');Progression.award(progression,500)}updateHUD();persist();}
let audio;function sound(gun){try{audio ||= new(window.AudioContext||window.webkitAudioContext)();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.type='sawtooth';osc.frequency.setValueAtTime(gun?150:85,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(25,audio.currentTime+.13);gain.gain.setValueAtTime(.055,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.17);osc.start();osc.stop(audio.currentTime+.18)}catch{}}
const ray=new THREE.Raycaster();function attack(){if(cooldown>0)return;const w=weapons[selected];cooldown=w.cooldown;swing=1;sound(w.gun);const dir=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));let target=player.position.clone().addScaledVector(dir,1.8);target.y+=1.1;
if(w.gun){ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects(blocks.filter(b=>b.alive).map(b=>b.mesh));target=hits.length?hits[0].point:ray.ray.at(60,new THREE.Vector3());const start=player.position.clone().add(new THREE.Vector3(.4,1.2,0));const g=new THREE.BufferGeometry().setFromPoints([start,target]);const line=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xcaff68}));scene.add(line);effects.push({mesh:line,life:.1})}
let count=0;for(const b of blocks){if(!b.alive)continue;const dist=b.mesh.position.distanceTo(target);if(dist<w.radius){b.hp-=w.power;if(b.hp<=0){shatter(b,dir);count++}else{b.mesh.rotation.z=(Math.random()-.5)*.12}}}
if(count){shake=.15;$('hitmark').style.opacity=1;setTimeout(()=>$('hitmark').style.opacity=0,110)}else if(!w.gun)toast('Move closer to a wall and swing.');}
function support(dt){for(const b of blocks){if(!b.alive||b.mesh.position.y<.36)continue;const p=b.mesh.position;const supported=blocks.some(o=>o.alive&&o!==b&&Math.abs(o.mesh.position.x-p.x)<.7&&Math.abs(o.mesh.position.z-p.z)<.5&&p.y-o.mesh.position.y>.1&&p.y-o.mesh.position.y<.8);if(!supported){b.vy-=12*dt;p.y+=b.vy*dt;if(p.y<=.34){p.y=.34;shatter(b,new THREE.Vector3((Math.random()-.5)*2,0,(Math.random()-.5)*2))}}}}
const keys={};let firing=false,fallback=false,paused=false,dragLook=false;function active(){return started&&!paused&&!$('armory').open&&(fallback||document.pointerLockElement===$('game'))}
function lock(){started=true;paused=false;$('play').hidden=true;try{const request=$('game').requestPointerLock?.();if(request&&request.catch)request.catch(enableFallback);else if(!$('game').requestPointerLock)enableFallback()}catch{enableFallback()}} function enableFallback(){fallback=true;$('pauseHint').hidden=true;toast('Mouse capture unavailable: hold right mouse to look, or use arrow keys.');} document.addEventListener('contextmenu',e=>e.preventDefault());
$('play').onclick=lock;$('game').onclick=()=>{if(!$('armory').open&&!active())lock()};document.addEventListener('pointerlockchange',()=>{$('pauseHint').hidden=!started||active()||$('armory').open;keys.w=keys.a=keys.s=keys.d=false;firing=false});
document.addEventListener('mousemove',e=>{if(active()&&(!fallback||dragLook)){yaw-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch+e.movementY*.002,-.45,.9)}});
document.addEventListener('mousedown',e=>{if(e.button===2)dragLook=true;if(active()&&e.button===0){firing=true;attack()}});document.addEventListener('mouseup',()=>{firing=false;dragLook=false});window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=false);firing=false;persist()});
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if([' ','arrowup','arrowdown'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='escape'&&fallback){paused=!paused;$('pauseHint').hidden=!paused;firing=false}if(k==='q'){$('armory').open?closeArmory():openArmory()}if(k==='r'&&active()){build();toast('Fresh walls. Same bad intentions.')}if(k===' '&&active()&&grounded){vy=7;grounded=false}if(k>='1'&&k<='9'&&active()){const n=Number(k)-1;if(n<level()){selected=n;updateHUD();persist()}}});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function openArmory(){document.exitPointerLock?.();$('armory').showModal();$('pauseHint').hidden=true;$('weapons').innerHTML='';weapons.forEach((w,i)=>{const btn=document.createElement('button');btn.className='weapon-card'+(w.level>level()?' locked':'')+(i===selected?' selected':'');btn.disabled=w.level>level();btn.innerHTML=`<small>${String(i+1).padStart(2,'0')} / ${w.gun?'RANGED':i>19?'POWER':'MELEE'}</small><strong>${w.name}</strong><em>${w.level>level()?'LOCKED · LEVEL '+w.level:i===selected?'EQUIPPED ↗':'EQUIP WEAPON ↗'}</em>`;btn.onclick=()=>{selected=i;updateHUD();persist();closeArmory();toast(w.name+' equipped.')};$('weapons').appendChild(btn)})}
function closeArmory(){$('armory').close();lock()}$('armoryButton').onclick=openArmory;$('closeArmory').onclick=closeArmory;$('reset').onclick=()=>{build();toast('Yard rebuilt. Your level and arsenal are saved.')};$('armory').addEventListener('close',()=>{$('pauseHint').hidden=!started||active()});
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.035);last=now;clock+=dt;const running=active();if(running){yaw+=((keys.arrowleft?1:0)-(keys.arrowright?1:0))*dt*1.7;pitch=THREE.MathUtils.clamp(pitch+((keys.arrowdown?1:0)-(keys.arrowup?1:0))*dt,-.45,.9);cooldown=Math.max(0,cooldown-dt);if(firing)attack();let mx=(keys.d?1:0)-(keys.a?1:0),mz=(keys.s?1:0)-(keys.w?1:0);const n=Math.hypot(mx,mz)||1;mx/=n;mz/=n;const speed=keys.shift?8:4.7,dx=(mx*Math.cos(yaw)+mz*Math.sin(yaw))*speed*dt,dz=(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*speed*dt;const pos=player.position;function blocked(x,z){return blocks.some(b=>b.alive&&Math.abs(b.mesh.position.x-x)<.85&&Math.abs(b.mesh.position.z-z)<.6&&b.mesh.position.y>pos.y+.1&&b.mesh.position.y<pos.y+1.9)}if(!blocked(pos.x+dx,pos.z))pos.x=THREE.MathUtils.clamp(pos.x+dx,-20,20);if(!blocked(pos.x,pos.z+dz))pos.z=THREE.MathUtils.clamp(pos.z+dz,-17,17);vy-=19*dt;pos.y=Math.max(0,pos.y+vy*dt);grounded=pos.y===0;if(grounded)vy=0;player.rotation.y=yaw;legL.rotation.x=Math.sin(clock*12)*(mx||mz?.55:0);legR.rotation.x=-legL.rotation.x;legL.userData.knee.rotation.x=Math.max(0,-legL.rotation.x)*.8;legR.userData.knee.rotation.x=Math.max(0,-legR.rotation.x)*.8;leftArm.rotation.x=-legL.rotation.x*.7;support(dt);
for(let i=fragments.length-1;i>=0;i--){const b=fragments[i];b.life-=dt;b.v.y-=18*dt;b.mesh.position.addScaledVector(b.v,dt);b.mesh.rotation.x+=b.rot.x*dt;b.mesh.rotation.z+=b.rot.z*dt;if(b.mesh.position.y<.15){b.mesh.position.y=.15;b.v.y=Math.abs(b.v.y)*.3;b.v.x*=.88;b.v.z*=.88;b.rot.multiplyScalar(.8)}if(b.life<1)b.mesh.scale.multiplyScalar(1-dt*2);if(b.life<=0){scene.remove(b.mesh);fragments.splice(i,1)}}}
swing=Math.max(0,swing-dt*4);arm.rotation.x=-Math.sin(swing*Math.PI)*1.8;for(let i=effects.length-1;i>=0;i--){effects[i].life-=dt;if(effects[i].life<=0){scene.remove(effects[i].mesh);effects[i].mesh.geometry.dispose();effects[i].mesh.material.dispose();effects.splice(i,1)}}
const distance=7.5,offset=new THREE.Vector3(Math.sin(yaw)*distance*Math.cos(pitch),3+Math.sin(pitch)*distance,Math.cos(yaw)*distance*Math.cos(pitch));const desired=player.position.clone().add(offset);camera.position.lerp(desired,1-Math.exp(-12*dt));const look=player.position.clone().add(new THREE.Vector3(-Math.sin(yaw)*3,1.1,-Math.cos(yaw)*3));shake=Math.max(0,shake-dt);if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}camera.lookAt(look);$('debris').textContent=String(fragments.filter(b=>b.v.lengthSq()>.4).length).padStart(2,'0');if(clock>toastUntil)$('toast').style.opacity=0;renderer.render(scene,camera);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});window.addEventListener('pagehide',persist);build();camera.position.set(0,5,18);requestAnimationFrame(frame);
