'use strict';
const upgrades={particles:[],projectiles:[],barrels:[],decor:new THREE.Group(),combo:0,comboUntil:0,best:0,charge:0,runTime:0,contract:0,contractStart:0,contractClaims:0,radarTime:0,lastWeapon:-1,muted:false,sensitivity:1,quality:'high',aim:false,finished:false};
const contracts=[{name:'Bring it down',goal:30,reward:120},{name:'Demolition crew',goal:60,reward:250},{name:'Wrecking machine',goal:100,reward:450}];
function initUpgrade(){scene.add(upgrades.decor);try{const prefs=JSON.parse(localStorage.getItem('destruction-settings')||'{}');upgrades.muted=!!prefs.muted;upgrades.sensitivity=Math.max(.3,Math.min(2,Number(prefs.sensitivity)||1));upgrades.quality=prefs.quality==='low'?'low':'high'}catch{}
 $('sensitivity').value=upgrades.sensitivity;$('mute').checked=upgrades.muted;$('quality').value=upgrades.quality;applySettings();
 $('settingsButton').onclick=()=>{pauseForMenu();$('settingsDialog').showModal()};$('closeSettings').onclick=()=>{$('settingsDialog').close();lock()};
 for(const id of ['sensitivity','mute','quality'])$(id).onchange=()=>{upgrades.sensitivity=Number($('sensitivity').value);upgrades.muted=$('mute').checked;upgrades.quality=$('quality').value;applySettings();localStorage.setItem('destruction-settings',JSON.stringify({sensitivity:upgrades.sensitivity,muted:upgrades.muted,quality:upgrades.quality}))};
 $('weaponSearch').oninput=renderArsenal;$('weaponFilter').onchange=renderArsenal;
 $('nextMap').onclick=()=>{$('runDialog').close();openMaps()};$('replayMap').onclick=()=>{$('runDialog').close();build();lock()};
 document.addEventListener('wheel',e=>{if(!active())return;e.preventDefault();selected=(selected+(e.deltaY>0?1:-1)+level())%level();updateHUD();persist()},{passive:false});
 document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target?.tagName))return;if(e.key.toLowerCase()==='e'&&active())shockwave();if(e.key.toLowerCase()==='f'&&!e.repeat){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('Fullscreen unavailable in this browser.'))}});
}
function applySettings(){renderer.setPixelRatio(Math.min(devicePixelRatio,upgrades.quality==='low'?1:1.7));renderer.shadowMap.enabled=upgrades.quality!=='low';}
function disposeFX(p){scene.remove(p.mesh);if(p.mesh.geometry!==geo&&p.mesh.geometry!==roundGeo)p.mesh.geometry.dispose();if(p.ownMaterial)p.mesh.material.dispose();}
function resetUpgrade(){for(const b of blocks){const p=b.mesh.position;b.supporters=blocks.filter(o=>o!==b&&Math.abs(o.mesh.position.x-p.x)<.7&&Math.abs(o.mesh.position.z-p.z)<.5&&p.y-o.mesh.position.y>.1&&p.y-o.mesh.position.y<.8);}for(const p of [...upgrades.particles,...upgrades.projectiles])disposeFX(p);upgrades.particles=[];upgrades.projectiles=[];upgrades.barrels=[];while(upgrades.decor.children.length){const c=upgrades.decor.children[0];upgrades.decor.remove(c);c.traverse(o=>{if(o.isMesh&&o.geometry!==geo&&o.geometry!==roundGeo)o.geometry.dispose()})}upgrades.combo=0;upgrades.best=0;upgrades.charge=0;upgrades.runTime=0;upgrades.finished=false;upgrades.contract=0;upgrades.contractStart=0;upgrades.contractClaims=0;
 const palette={works:['#364451','#f2b25d'],canyon:['#805b46','#dbb278'],frost:['#779cab','#dff6ff'],neon:['#1c2446','#7af9df']}[mapId];
 // A different skyline for each district, outside the walkable arena.
 for(let i=0;i<16;i++){const x=(i-7.5)*4.5,z=-27-(i%3)*3,h=mapId==='neon'?8+(i%5)*4:mapId==='canyon'?5+(i%4)*3:4+(i%3)*2;box(x,h/2,z,3.4,h,3.4,palette[0],upgrades.decor);if(mapId==='neon')for(let y=2;y<h;y+=2)box(x,y,z+1.72,2.6,.12,.03,palette[1],upgrades.decor);if(mapId==='frost')box(x,h,z,3.7,.3,3.7,palette[1],upgrades.decor);}
 for(const [x,z] of [[-8,6],[5,4],[-3,-8],[12,-5]]){const group=new THREE.Group();group.position.set(x,.55,z);upgrades.decor.add(group);const body=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,1.1,12),mat('#d96440'));body.castShadow=true;group.add(body);for(const y of [-.32,.32])box(0,y,0,.72,.07,.72,'#3b4248',group);box(0,.05,.35,.3,.25,.02,'#ffda74',group);upgrades.barrels.push({mesh:group,alive:true});}
 scene.fog.density=mapId==='neon'?.017:.009;sun.intensity=mapId==='neon'?1.6:3;updateContract();
}
function burst(point,color,count=14){const budget=upgrades.quality==='low'?60:140;for(let i=0;i<count;i++){const material=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8});const mesh=new THREE.Mesh(roundGeo,material);mesh.position.copy(point);mesh.scale.setScalar(.06+Math.random()*.1);scene.add(mesh);upgrades.particles.push({mesh,v:new THREE.Vector3((Math.random()-.5)*7,Math.random()*5,(Math.random()-.5)*7),life:.5+Math.random()*.5,max:1,ownMaterial:true});}while(upgrades.particles.length>budget)disposeFX(upgrades.particles.shift());}
function ring(point,color,size){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,16,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.23,wireframe:true}));mesh.position.copy(point);scene.add(mesh);upgrades.particles.push({mesh,life:.4,max:.4,ring:size,ownMaterial:true});}
function tracer(start,end,color){const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,end]),new THREE.LineBasicMaterial({color,transparent:true,opacity:1}));scene.add(mesh);upgrades.particles.push({mesh,life:.1,max:.1,ownMaterial:true});}
function damageArea(point,radius,power,direction){let hit=0;for(const b of blocks){if(!b.alive||b.mesh.position.distanceTo(point)>radius)continue;b.hp-=power;hit++;if(b.hp<=0)shatter(b,direction);else{b.mesh.scale.set(1.12*(.96+.04*b.hp/b.maxHP),.65,.65);}}
 for(const barrel of upgrades.barrels){if(barrel.alive&&barrel.mesh.position.distanceTo(point)<radius+.4){barrel.alive=false;const position=barrel.mesh.position.clone();barrel.mesh.visible=false;ring(position,'#ffac55',5);burst(position,'#ffb15e',25);damageArea(position,4.3,18,direction);shake=.35;}}
 if(hit){$('hitmark').style.opacity=1;upgrades.hitUntil=clock+.1;shake=Math.max(shake,.1);}return hit;}
function fireWeapon(){if(cooldown>0)return;const w=weapons[selected];cooldown=w.cooldown;swing=1;sound(w.gun);camera.position.copy(player.position).add(new THREE.Vector3(0,1.75,0));camera.rotation.set(-pitch,yaw,0,'YXZ');camera.updateMatrixWorld();scene.updateMatrixWorld(true);const dir=camera.getWorldDirection(new THREE.Vector3()),origin=camera.position.clone();const start=new THREE.Vector3(.25,-.17,-.6).applyMatrix4(camera.matrixWorld);
 if(w.kind==='rocket'||w.kind==='vortex'){const mesh=new THREE.Mesh(roundGeo,new THREE.MeshBasicMaterial({color:w.color}));mesh.scale.setScalar(.14);mesh.position.copy(origin).addScaledVector(dir,.5);scene.add(mesh);upgrades.projectiles.push({mesh,dir,w,life:4,ownMaterial:true});return;}
 if(!w.gun){const point=origin.clone().addScaledVector(dir,1.7);if(w.kind==='pulse')ring(point,w.color,w.radius);const hits=damageArea(point,w.radius,w.power,dir);if(hits)burst(point,w.color,10);return;}
 const pellets=w.kind==='shotgun'?7:1;for(let i=0;i<pellets;i++){const d=dir.clone();if(pellets>1)d.add(new THREE.Vector3((Math.random()-.5)*.13,(Math.random()-.5)*.13,(Math.random()-.5)*.13)).normalize();ray.set(origin,d);const targets=ray.intersectObjects(blocks.filter(b=>b.alive).map(b=>b.mesh));const point=targets.length?targets[0].point:origin.clone().addScaledVector(d,65);tracer(start,point,w.color);if(targets.length){damageArea(point,w.radius,w.power,d);burst(point,w.color,5);}for(const b of upgrades.barrels)if(b.alive&&ray.ray.distanceToPoint(b.mesh.position)<.5&&b.mesh.position.distanceTo(origin)<point.distanceTo(origin))damageArea(b.mesh.position,.6,w.power,d);if(w.kind==='beam')for(const hit of targets.slice(1,5))damageArea(hit.point,.7,w.power,d);}
}
function onBlockDestroyed(){upgrades.combo=clock<upgrades.comboUntil?upgrades.combo+1:1;upgrades.comboUntil=clock+3;upgrades.best=Math.max(upgrades.best,upgrades.combo);if(clock>=(upgrades.chargeLockUntil||0))upgrades.charge=Math.min(100,upgrades.charge+2.5);$('impactFlash').style.opacity=.35;upgrades.flashUntil=clock+.1;const contract=contracts[upgrades.contract%contracts.length];if(destroyed-upgrades.contractStart>=contract.goal){Progression.award(progression,Math.round(contract.reward*Rebirth.multiplier(prestige)));upgrades.contract++;upgrades.contractClaims++;upgrades.contractStart=destroyed;toast('CONTRACT COMPLETE · +'+contract.reward+' XP');}updateContract();}
function updateContract(){const c=contracts[upgrades.contract%contracts.length];$('contractName').textContent=c.name;$('contractProgress').textContent=Math.min(c.goal,destroyed-upgrades.contractStart)+' / '+c.goal+' blocks · +'+c.reward+' XP';}
function shockwave(){if(upgrades.charge<100){toast('Destroy blocks to charge your shockwave.');return;}upgrades.charge=0;upgrades.chargeLockUntil=clock+3;const center=player.position.clone().add(new THREE.Vector3(0,1,0));ring(center,'#baff63',8);burst(center,'#baff63',24);damageArea(center,7,20,new THREE.Vector3(0,1,-1));shake=.4;toast('SHOCKWAVE!');}
function finishRun(){if(upgrades.finished)return;upgrades.finished=true;pauseForMenu();$('runSummary').textContent=initialCount+' blocks destroyed in '+Math.floor(upgrades.runTime/60)+'m '+Math.floor(upgrades.runTime%60)+'s. Best chain: '+upgrades.best+'. Contracts completed: '+upgrades.contractClaims+'. +500 clear bonus XP!';$('runDialog').showModal();}
function updateUpgrade(dt,running){document.body.classList.toggle('playing',started);if(running)upgrades.runTime+=dt;const comboActive=clock<upgrades.comboUntil&&upgrades.combo>=3;$('combo').style.opacity=comboActive?1:0;$('comboCount').textContent=upgrades.combo+' CHAIN';$('comboLabel').textContent=Combat.rank(upgrades.combo);$('comboFill').style.width=Math.max(0,(upgrades.comboUntil-clock)/3*100)+'%';$('ability').textContent=upgrades.charge>=100?'E · SHOCKWAVE READY':'SHOCKWAVE '+Math.floor(upgrades.charge)+'% · BREAK TO CHARGE';if(clock>upgrades.hitUntil)$('hitmark').style.opacity=0;if(clock>upgrades.flashUntil)$('impactFlash').style.opacity=0;
 if(running){for(let i=upgrades.projectiles.length-1;i>=0;i--){const p=upgrades.projectiles[i],speed=p.w.kind==='vortex'?15:25,step=speed*dt;ray.set(p.mesh.position,p.dir);const hit=ray.intersectObjects(blocks.filter(b=>b.alive).map(b=>b.mesh))[0];p.life-=dt;if((hit&&hit.distance<step+.25)||p.life<=0||p.mesh.position.y<0){const point=hit&&hit.distance<step+.25?hit.point:p.mesh.position.clone();damageArea(point,p.w.radius,p.w.power*2,p.dir);ring(point,p.w.color,p.w.radius);burst(point,p.w.color,25);if(p.w.kind==='vortex')for(const f of fragments)if(f.mesh.position.distanceTo(point)<8)f.v.copy(point).sub(f.mesh.position).multiplyScalar(4);shake=.3;disposeFX(p);upgrades.projectiles.splice(i,1)}else p.mesh.position.addScaledVector(p.dir,step);}}
 for(let i=upgrades.particles.length-1;i>=0;i--){const p=upgrades.particles[i];p.life-=dt;p.mesh.material.opacity=Math.max(0,p.life/p.max)*(p.ring?.25:1);if(p.v){p.v.y-=9*dt;p.mesh.position.addScaledVector(p.v,dt)}if(p.ring)p.mesh.scale.setScalar((1-p.life/p.max)*p.ring);if(p.life<=0){disposeFX(p);upgrades.particles.splice(i,1)}}
 upgrades.radarTime-=dt;if(upgrades.radarTime<=0){upgrades.radarTime=.12;drawRadar();ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects(blocks.filter(b=>b.alive).map(b=>b.mesh))[0];const b=hit&&blocks.find(b=>b.mesh===hit.object);$('targetInfo').style.opacity=b?1:0;if(b){$('targetLabel').textContent=hit.distance.toFixed(1)+' M · '+(b.hp<=2?'FRAGILE':'REINFORCED');$('targetHealth').style.width=100*b.hp/b.maxHP+'%';}}
 camera.fov=THREE.MathUtils.lerp(camera.fov,running&&keys.shift?83:75,.08);camera.updateProjectionMatrix();
}
function drawRadar(){const c=$('radar').getContext('2d'),w=150;c.clearRect(0,0,w,w);c.strokeStyle='#9bbaac30';for(let i=25;i<150;i+=25){c.beginPath();c.moveTo(i,0);c.lineTo(i,150);c.moveTo(0,i);c.lineTo(150,i);c.stroke()}c.fillStyle='#adbdc8';for(const b of blocks)if(b.alive)c.fillRect(75+b.mesh.position.x*3,75+b.mesh.position.z*3,3,2);c.fillStyle='#ff925d';for(const b of upgrades.barrels)if(b.alive)c.fillRect(73+b.mesh.position.x*3,73+b.mesh.position.z*3,5,5);c.save();c.translate(75+player.position.x*3,75+player.position.z*3);c.rotate(-yaw);c.fillStyle='#c4ff64';c.beginPath();c.moveTo(0,-6);c.lineTo(4,4);c.lineTo(0,2);c.lineTo(-4,4);c.fill();c.restore();}
function renderArsenal(){const search=$('weaponSearch').value.toLowerCase(),filter=$('weaponFilter').value;$('weapons').innerHTML='';for(const [i,w] of weapons.entries()){if(!w.name.toLowerCase().includes(search)||filter==='unlocked'&&w.level>level()||filter==='ranged'&&!w.gun||filter==='melee'&&w.gun)continue;const btn=document.createElement('button');btn.className='weapon-card'+(w.level>level()?' locked':'')+(i===selected?' selected':'');btn.disabled=w.level>level();btn.innerHTML='<small>'+String(i+1).padStart(2,'0')+' / '+w.kind.toUpperCase()+'</small><strong>'+w.name+'</strong><em>POWER '+w.power+' · '+(1/w.cooldown).toFixed(1)+'/SEC<br>'+(w.level>level()?'LEVEL '+w.level:i===selected?'EQUIPPED':'EQUIP ↗')+'</em>';btn.onclick=()=>{selected=i;updateHUD();persist();closeArmory();toast(w.name+' equipped.')};$('weapons').appendChild(btn)}if(!$('weapons').children.length)$('weapons').textContent='No weapons match your search.';}
function buildWeaponModel(){if(upgrades.lastWeapon===selected)return;upgrades.lastWeapon=selected;while(held.children.length)held.remove(held.children[0]);const w=weapons[selected],steel='#8495a2',dark='#25333d';const part=(x,y,z,a,b,c,color)=>box(x,y,z,a,b,c,color,held);
 if(w.kind==='melee'){part(.3,-.1,-.62,.065,.66,.065,'#79563a');for(let i=0;i<5;i++)part(.3,-.3+i*.04,-.62,.075,.02,.075,dark);if(/Axe|Pickaxe/.test(w.name)){part(.25,.17,-.62,.28,.27,.06,steel);part(.13,.16,-.62,.04,.3,.08,'#e4edf0')}else if(/Bat|Crowbar/.test(w.name)){part(.3,.12,-.62,.10,.6,.10,steel)}else{part(.3,.21,-.62,.32,.19,.17,steel);part(.10,.21,-.62,.05,.22,.2,'#d9e2e4');part(.49,.21,-.62,.05,.22,.2,'#d9e2e4');part(.3,.21,-.71,.12,.10,.025,'#c2ff69')}}
 else if(w.kind==='pulse'||w.kind==='vortex'){part(.3,-.17,-.66,.23,.26,.3,dark);for(let i=0;i<3;i++)part(.3,-.17,-.76-i*.06,.26-i*.025,.29-i*.025,.025,w.color);part(.3,-.17,-.96,.13,.13,.1,w.color)}
 else{const heavy=w.kind==='rocket';part(.3,-.2,-.69,heavy?.26:.18,heavy?.26:.18,heavy?.65:.47,dark);part(.3,-.13,-.66,.13,.045,.38,steel);part(.3,-.34,-.55,.12,.25,.13,dark);part(.3,-.2,-1.03,heavy?.2:.07,heavy?.2:.07,.32,steel);part(.3,-.2,-1.21,heavy?.22:.10,heavy?.22:.10,.04,dark);if(w.kind==='shotgun')part(.38,-.2,-1.03,.07,.07,.35,steel);if(w.kind==='beam')for(let i=0;i<4;i++)part(.3,-.2,-.6-i*.11,.20,.21,.02,w.color);part(.3,-.08,-.64,.05,.08,.07,w.color);}
}
